### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by FelixINX** [etiennedub/LecteurOPUS#1]
Bonjour!

J'aimerais améliorer l'application (y ajouter des circuits) mais mes cartes OPUS ne semblent pas donner de l'information (circuit et opérateur 0...).

Est-il possible que vous communiquiez avec moi par courriel?

Merci!

**Comment by austinhuang0131** [comment]
The app now allows you to easily fill out incomplete info. Press the `+` next to an "Inconnu".

Also, don't leave your email in the public (Even if masked).
